server:
  port: 8081



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: my-super-secret-key-for-jwt-project
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://serviceregistry:8761/eureka