server:
  port: 8088

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/notification_db
  
  # Uncomment later after Kafka testing
  #
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: yourmail@gmail.com
  #    password: app-password
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  kafka:

    bootstrap-servers: localhost:9092

    consumer:

      group-id: notification

      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:

        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer

        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: "*"

        spring.json.use.type.headers: false

        spring.json.value.default.type: com.org.projectmanagement.notificationservice.event.UserCreatedEvent

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka